@server=http://localhost:4004
@username=alice
@password=


### DeviceGroupListReport
# @name DeviceGroupListReport_GET
GET {{server}}/odata/v4/device-group-list-report-services/DeviceGroupListReport
Authorization: Basic {{username}}:{{password}}


### DeviceGroupListReport
# @name DeviceGroupListReport_POST
POST {{server}}/odata/v4/device-group-list-report-services/DeviceGroupListReport
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30968872-de58-436a-afb5-1b3fb98e53a9",
  "InspectionLot": "InspectionLot-30968872",
  "Material": "Material-30968872",
  "SerialBatchNumber": "SerialBatchNumber-30968872",
  "DeviceGroupID": "DeviceGroupID-30968872",
  "DeviceGroup": "DeviceGroup-30968872",
  "Dsc": "Dsc-30968872"
}


### DeviceGroupListReport
# @name DeviceGroupListReport_PATCH
PATCH {{server}}/odata/v4/device-group-list-report-services/DeviceGroupListReport/30968872-de58-436a-afb5-1b3fb98e53a9
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "30968872-de58-436a-afb5-1b3fb98e53a9",
  "InspectionLot": "InspectionLot-30968872",
  "Material": "Material-30968872",
  "SerialBatchNumber": "SerialBatchNumber-30968872",
  "DeviceGroupID": "DeviceGroupID-30968872",
  "DeviceGroup": "DeviceGroup-30968872",
  "Dsc": "Dsc-30968872"
}


### DeviceGroupListReport
# @name DeviceGroupListReport_DELETE
DELETE {{server}}/odata/v4/device-group-list-report-services/DeviceGroupListReport/30968872-de58-436a-afb5-1b3fb98e53a9
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
