@server=http://localhost:4004
@username=alice
@password=


### FormStatus
# @name FormStatus_GET
GET {{server}}/odata/v4/form-status-services/FormStatus
Authorization: Basic {{username}}:{{password}}


### FormStatus
# @name FormStatus_POST
POST {{server}}/odata/v4/form-status-services/FormStatus
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26345383-e376-4bc5-b654-0c46dc0f5df4",
  "FormId": "FormId-26345383",
  "IsLocked": false,
  "UserName": "UserName-26345383",
  "LockedDateTime": "2007-01-19T00:00:00.000Z"
}


### FormStatus
# @name FormStatus_PATCH
PATCH {{server}}/odata/v4/form-status-services/FormStatus/26345383-e376-4bc5-b654-0c46dc0f5df4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26345383-e376-4bc5-b654-0c46dc0f5df4",
  "FormId": "FormId-26345383",
  "IsLocked": false,
  "UserName": "UserName-26345383",
  "LockedDateTime": "2007-01-19T00:00:00.000Z"
}


### FormStatus
# @name FormStatus_DELETE
DELETE {{server}}/odata/v4/form-status-services/FormStatus/26345383-e376-4bc5-b654-0c46dc0f5df4
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
