@server=http://localhost:4004
@username=alice
@password=


### GetElectrialUser
# @name GetElectrialUser_GET
GET {{server}}/odata/v4/get-electrial-user-services/GetElectrialUser
Authorization: Basic {{username}}:{{password}}


### GetElectrialUser
# @name GetElectrialUser_POST
POST {{server}}/odata/v4/get-electrial-user-services/GetElectrialUser
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "20656218-0bf2-4e03-b717-44e22619ed1b",
  "ElectrialUserName": "ElectrialUserName-20656218"
}


### GetElectrialUser
# @name GetElectrialUser_PATCH
PATCH {{server}}/odata/v4/get-electrial-user-services/GetElectrialUser/20656218-0bf2-4e03-b717-44e22619ed1b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "20656218-0bf2-4e03-b717-44e22619ed1b",
  "ElectrialUserName": "ElectrialUserName-20656218"
}


### GetElectrialUser
# @name GetElectrialUser_DELETE
DELETE {{server}}/odata/v4/get-electrial-user-services/GetElectrialUser/20656218-0bf2-4e03-b717-44e22619ed1b
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
