@server=http://localhost:4004
@username=alice
@password=


### InspectionQcReport2
# @name InspectionQcReport2_GET
GET {{server}}/odata/v4/inspection-qcreport2/InspectionQcReport2
Authorization: Basic {{username}}:{{password}}


### InspectionQcReport2
# @name InspectionQcReport2_POST
POST {{server}}/odata/v4/inspection-qcreport2/InspectionQcReport2
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "79860118-f359-42a9-95ed-0e93951aa1d4",
  "lineid": 7986011,
  "ParentParameterCode": "ParentParameterCode-7986011",
  "ParentParameterName": "ParentParameterName-7986011",
  "ParameterCode": "ParameterCode-7986011",
  "ParameterName": "ParameterName-7986011",
  "Attribute": "Attribute-7986011",
  "Lowervalue": "Lowervalue-7986011",
  "Uppervalue": "Uppervalue-7986011",
  "Observation": "Observation-7986011",
  "UOM": "UOM-7986011",
  "Status": "Status-7986011"
}


### InspectionQcReport2
# @name InspectionQcReport2_PATCH
PATCH {{server}}/odata/v4/inspection-qcreport2/InspectionQcReport2(ID=79860118-f359-42a9-95ed-0e93951aa1d4,lineid=7986011)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "79860118-f359-42a9-95ed-0e93951aa1d4",
  "lineid": 7986011,
  "ParentParameterCode": "ParentParameterCode-7986011",
  "ParentParameterName": "ParentParameterName-7986011",
  "ParameterCode": "ParameterCode-7986011",
  "ParameterName": "ParameterName-7986011",
  "Attribute": "Attribute-7986011",
  "Lowervalue": "Lowervalue-7986011",
  "Uppervalue": "Uppervalue-7986011",
  "Observation": "Observation-7986011",
  "UOM": "UOM-7986011",
  "Status": "Status-7986011"
}


### InspectionQcReport2
# @name InspectionQcReport2_DELETE
DELETE {{server}}/odata/v4/inspection-qcreport2/InspectionQcReport2(ID=79860118-f359-42a9-95ed-0e93951aa1d4,lineid=7986011)
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
