@server=http://localhost:4004
@username=alice
@password=


### ProductQualityClearance
# @name ProductQualityClearance_GET
GET {{server}}/odata/v4/product-quality-clearance/ProductQualityClearance
Authorization: Basic {{username}}:{{password}}


### ProductQualityClearance
# @name ProductQualityClearance_POST
POST {{server}}/odata/v4/product-quality-clearance/ProductQualityClearance
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17005047-b5e5-4fdd-b8a7-c4d5398243ba",
  "OrderType": "OrderType-17005047",
  "MachinePartCode": "MachinePartCode-17005047",
  "DetailDescription": "DetailDescription-17005047",
  "Serial": "Serial-17005047",
  "Inspection": "Inspection-17005047",
  "CertificateType": "CertificateType-17005047",
  "CertificateNo": "CertificateNo-17005047",
  "CertificationType": "CertificationType-17005047",
  "MachineType": "MachineType-17005047",
  "ProductionOrder": "ProductionOrder-17005047",
  "MachineModel": "MachineModel-17005047",
  "ManufacturingCode": "ManufacturingCode-17005047",
  "MachineSeries": "MachineSeries-17005047",
  "ManufacturingCodeRevision": "ManufacturingCodeRevision-17005047",
  "ElectricalQA": "ElectricalQA-17005047",
  "MechanicalQA": "MechanicalQA-17005047",
  "deviation": "deviation-17005047",
  "deviationNo": "deviationNo-17005047",
  "ElectricalPerson": "ElectricalPerson-17005047",
  "ProductSpecilist": "ProductSpecilist-17005047",
  "FinalClearnsby": "FinalClearnsby-17005047",
  "FinalApprovalby": "FinalApprovalby-17005047",
  "LineItem": [
    {
      "ID": "23246808-53a0-4f8d-88bc-458c8258853d",
      "DocumentNum": "DocumentNum-23246808",
      "IsDocumentAtteched": "IsDocumentAtteched-23246808",
      "IsApplicable": "IsApplicable-23246808"
    },
    {
      "ID": "23246809-c954-40ff-8a67-dfe71ff82db7",
      "DocumentNum": "DocumentNum-23246809",
      "IsDocumentAtteched": "IsDocumentAtteched-23246809",
      "IsApplicable": "IsApplicable-23246809"
    }
  ]
}


### ProductQualityClearance
# @name ProductQualityClearance_PATCH
PATCH {{server}}/odata/v4/product-quality-clearance/ProductQualityClearance/17005047-b5e5-4fdd-b8a7-c4d5398243ba
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "17005047-b5e5-4fdd-b8a7-c4d5398243ba",
  "OrderType": "OrderType-17005047",
  "MachinePartCode": "MachinePartCode-17005047",
  "DetailDescription": "DetailDescription-17005047",
  "Serial": "Serial-17005047",
  "Inspection": "Inspection-17005047",
  "CertificateType": "CertificateType-17005047",
  "CertificateNo": "CertificateNo-17005047",
  "CertificationType": "CertificationType-17005047",
  "MachineType": "MachineType-17005047",
  "ProductionOrder": "ProductionOrder-17005047",
  "MachineModel": "MachineModel-17005047",
  "ManufacturingCode": "ManufacturingCode-17005047",
  "MachineSeries": "MachineSeries-17005047",
  "ManufacturingCodeRevision": "ManufacturingCodeRevision-17005047",
  "ElectricalQA": "ElectricalQA-17005047",
  "MechanicalQA": "MechanicalQA-17005047",
  "deviation": "deviation-17005047",
  "deviationNo": "deviationNo-17005047",
  "ElectricalPerson": "ElectricalPerson-17005047",
  "ProductSpecilist": "ProductSpecilist-17005047",
  "FinalClearnsby": "FinalClearnsby-17005047",
  "FinalApprovalby": "FinalApprovalby-17005047",
  "LineItem": [
    {
      "ID": "23246808-53a0-4f8d-88bc-458c8258853d",
      "DocumentNum": "DocumentNum-23246808",
      "IsDocumentAtteched": "IsDocumentAtteched-23246808",
      "IsApplicable": "IsApplicable-23246808"
    },
    {
      "ID": "23246809-c954-40ff-8a67-dfe71ff82db7",
      "DocumentNum": "DocumentNum-23246809",
      "IsDocumentAtteched": "IsDocumentAtteched-23246809",
      "IsApplicable": "IsApplicable-23246809"
    }
  ]
}


### ProductQualityClearance
# @name ProductQualityClearance_DELETE
DELETE {{server}}/odata/v4/product-quality-clearance/ProductQualityClearance/17005047-b5e5-4fdd-b8a7-c4d5398243ba
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### LineInfo
# @name LineInfo_GET
GET {{server}}/odata/v4/product-quality-clearance/LineInfo
Authorization: Basic {{username}}:{{password}}


### LineInfo
# @name LineInfo_POST
POST {{server}}/odata/v4/product-quality-clearance/LineInfo
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23246808-53a0-4f8d-88bc-458c8258853d",
  "DocumentNum": "DocumentNum-23246808",
  "IsDocumentAtteched": "IsDocumentAtteched-23246808",
  "IsApplicable": "IsApplicable-23246808"
}


### LineInfo
# @name LineInfo_PATCH
PATCH {{server}}/odata/v4/product-quality-clearance/LineInfo/23246808-53a0-4f8d-88bc-458c8258853d
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "23246808-53a0-4f8d-88bc-458c8258853d",
  "DocumentNum": "DocumentNum-23246808",
  "IsDocumentAtteched": "IsDocumentAtteched-23246808",
  "IsApplicable": "IsApplicable-23246808"
}


### LineInfo
# @name LineInfo_DELETE
DELETE {{server}}/odata/v4/product-quality-clearance/LineInfo/23246808-53a0-4f8d-88bc-458c8258853d
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
