@server=http://localhost:4004
@username=alice
@password=


### RecordResultDeviceTagging
# @name RecordResultDeviceTagging_GET
GET {{server}}/odata/v4/record-result-device-tagging-services/RecordResultDeviceTagging
Authorization: Basic {{username}}:{{password}}


### RecordResultDeviceTagging
# @name RecordResultDeviceTagging_POST
POST {{server}}/odata/v4/record-result-device-tagging-services/RecordResultDeviceTagging
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "946743cf-ed16-4b51-9a56-48237f0d8fad",
  "DeviceSelect": false,
  "DeviceID": "DeviceID-946743",
  "DeviceDescription": "DeviceDescription-946743",
  "DeviceGroup": "DeviceGroup-946743",
  "Serial": "Serial-946743",
  "DSerial": "DSerial-946743",
  "createdAt": "2008-04-10T00:00:00.000Z",
  "createdBy": "createdBy.kaif@example.org",
  "modifiedAt": "2019-01-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.kaif@example.net"
}


### RecordResultDeviceTagging
# @name RecordResultDeviceTagging_PATCH
PATCH {{server}}/odata/v4/record-result-device-tagging-services/RecordResultDeviceTagging/946743cf-ed16-4b51-9a56-48237f0d8fad
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "946743cf-ed16-4b51-9a56-48237f0d8fad",
  "DeviceSelect": false,
  "DeviceID": "DeviceID-946743",
  "DeviceDescription": "DeviceDescription-946743",
  "DeviceGroup": "DeviceGroup-946743",
  "Serial": "Serial-946743",
  "DSerial": "DSerial-946743",
  "createdAt": "2008-04-10T00:00:00.000Z",
  "createdBy": "createdBy.kaif@example.org",
  "modifiedAt": "2019-01-28T00:00:00.000Z",
  "modifiedBy": "modifiedBy.kaif@example.net"
}


### RecordResultDeviceTagging
# @name RecordResultDeviceTagging_DELETE
DELETE {{server}}/odata/v4/record-result-device-tagging-services/RecordResultDeviceTagging/946743cf-ed16-4b51-9a56-48237f0d8fad
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
