@server=http://localhost:4004
@username=alice
@password=


### RecordResultSAPHead
# @name RecordResultSAPHead_GET
GET {{server}}/odata/v4/record-result-sap/RecordResultSAPHead
Authorization: Basic {{username}}:{{password}}


### RecordResultSAPHead
# @name RecordResultSAPHead_POST
POST {{server}}/odata/v4/record-result-sap/RecordResultSAPHead
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15316918-991c-4879-860b-2925b51287a1",
  "InspectionLot": "InspectionLot-15316918",
  "Material": "Material-15316918",
  "Plant": "Plant-15316918",
  "ManagedBy": "ManagedBy-15316918",
  "PostDate": "2009-08-07",
  "EOI": "EOI-15316918",
  "Quantity": 91.26,
  "AcceptedQuantity": 75.14,
  "RejectedQuantity": 23.22,
  "Status": "Status-15316918",
  "UsageDecisionLevel": "UsageDecisionLevel-15316918",
  "QuantityScore": 45.29,
  "DecisionCatalog": 84,
  "UsageDecisionSelectedSet": "UsageDecisionSelectedSet-15316918",
  "UsageDecisionCodeGroup": "UsageDecisionCodeGroup-15316918",
  "UsageDecisionCode": "UsageDecisionCode-15316918",
  "UsageDecisionValuation": "UsageDecisionValuation-15316918",
  "UsageDecisionFollowupAction": "UsageDecisionFollowupAction-15316918",
  "SerialBatchDetails": [
    {
      "ID": "19196688-b832-4af8-8e27-49a877483332",
      "SerialBatchNumber": "SerialBatchNumber-19196688",
      "Quantity": 18.14,
      "Status": "Status-19196688",
      "UsageDecisionStockType": "UsageDecisionStockType-19196688",
      "StorageLocation": "StorageLocation-19196688",
      "InspectionPlanStatus": "InspectionPlanStatus-19196688",
      "ParametersDetails": [
        {
          "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
          "ParameterCode": "ParameterCode-24033749",
          "ParameterName": "ParameterName-24033749",
          "ParentParameterCode": "ParentParameterCode-24033749",
          "ParentParameterName": "ParentParameterName-24033749",
          "AttributeID": "AttributeID-24033749",
          "Attribute": "Attribute-24033749",
          "Observation": "Observation-24033749",
          "InstrumentId": "InstrumentId-24033749",
          "InstrumentDesc": "InstrumentDesc-24033749",
          "Status": "Status-24033749",
          "Remarks1": "Remarks1-24033749",
          "Remarks2": "Remarks2-24033749"
        },
        {
          "ID": "24033750-4d85-4b7d-aa00-4fcc7453baf4",
          "ParameterCode": "ParameterCode-24033750",
          "ParameterName": "ParameterName-24033750",
          "ParentParameterCode": "ParentParameterCode-24033750",
          "ParentParameterName": "ParentParameterName-24033750",
          "AttributeID": "AttributeID-24033750",
          "Attribute": "Attribute-24033750",
          "Observation": "Observation-24033750",
          "InstrumentId": "InstrumentId-24033750",
          "InstrumentDesc": "InstrumentDesc-24033750",
          "Status": "Status-24033750",
          "Remarks1": "Remarks1-24033750",
          "Remarks2": "Remarks2-24033750"
        }
      ]
    },
    {
      "ID": "19196689-8b96-4d1f-a13b-8322e9f71c11",
      "SerialBatchNumber": "SerialBatchNumber-19196689",
      "Quantity": 97.15,
      "Status": "Status-19196689",
      "UsageDecisionStockType": "UsageDecisionStockType-19196689",
      "StorageLocation": "StorageLocation-19196689",
      "InspectionPlanStatus": "InspectionPlanStatus-19196689",
      "ParametersDetails": [
        {
          "ID": "67407745-2071-4d52-ae2b-b102212c88f0",
          "ParameterCode": "ParameterCode-6740774",
          "ParameterName": "ParameterName-6740774",
          "ParentParameterCode": "ParentParameterCode-6740774",
          "ParentParameterName": "ParentParameterName-6740774",
          "AttributeID": "AttributeID-6740774",
          "Attribute": "Attribute-6740774",
          "Observation": "Observation-6740774",
          "InstrumentId": "InstrumentId-6740774",
          "InstrumentDesc": "InstrumentDesc-6740774",
          "Status": "Status-6740774",
          "Remarks1": "Remarks1-6740774",
          "Remarks2": "Remarks2-6740774"
        },
        {
          "ID": "6740775a-d563-4e0f-922b-5998b0c3fe0b",
          "ParameterCode": "ParameterCode-6740775",
          "ParameterName": "ParameterName-6740775",
          "ParentParameterCode": "ParentParameterCode-6740775",
          "ParentParameterName": "ParentParameterName-6740775",
          "AttributeID": "AttributeID-6740775",
          "Attribute": "Attribute-6740775",
          "Observation": "Observation-6740775",
          "InstrumentId": "InstrumentId-6740775",
          "InstrumentDesc": "InstrumentDesc-6740775",
          "Status": "Status-6740775",
          "Remarks1": "Remarks1-6740775",
          "Remarks2": "Remarks2-6740775"
        }
      ]
    }
  ]
}


### RecordResultSAPHead
# @name RecordResultSAPHead_PATCH
PATCH {{server}}/odata/v4/record-result-sap/RecordResultSAPHead/15316918-991c-4879-860b-2925b51287a1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15316918-991c-4879-860b-2925b51287a1",
  "InspectionLot": "InspectionLot-15316918",
  "Material": "Material-15316918",
  "Plant": "Plant-15316918",
  "ManagedBy": "ManagedBy-15316918",
  "PostDate": "2009-08-07",
  "EOI": "EOI-15316918",
  "Quantity": 91.26,
  "AcceptedQuantity": 75.14,
  "RejectedQuantity": 23.22,
  "Status": "Status-15316918",
  "UsageDecisionLevel": "UsageDecisionLevel-15316918",
  "QuantityScore": 45.29,
  "DecisionCatalog": 84,
  "UsageDecisionSelectedSet": "UsageDecisionSelectedSet-15316918",
  "UsageDecisionCodeGroup": "UsageDecisionCodeGroup-15316918",
  "UsageDecisionCode": "UsageDecisionCode-15316918",
  "UsageDecisionValuation": "UsageDecisionValuation-15316918",
  "UsageDecisionFollowupAction": "UsageDecisionFollowupAction-15316918",
  "SerialBatchDetails": [
    {
      "ID": "19196688-b832-4af8-8e27-49a877483332",
      "SerialBatchNumber": "SerialBatchNumber-19196688",
      "Quantity": 18.14,
      "Status": "Status-19196688",
      "UsageDecisionStockType": "UsageDecisionStockType-19196688",
      "StorageLocation": "StorageLocation-19196688",
      "InspectionPlanStatus": "InspectionPlanStatus-19196688",
      "ParametersDetails": [
        {
          "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
          "ParameterCode": "ParameterCode-24033749",
          "ParameterName": "ParameterName-24033749",
          "ParentParameterCode": "ParentParameterCode-24033749",
          "ParentParameterName": "ParentParameterName-24033749",
          "AttributeID": "AttributeID-24033749",
          "Attribute": "Attribute-24033749",
          "Observation": "Observation-24033749",
          "InstrumentId": "InstrumentId-24033749",
          "InstrumentDesc": "InstrumentDesc-24033749",
          "Status": "Status-24033749",
          "Remarks1": "Remarks1-24033749",
          "Remarks2": "Remarks2-24033749"
        },
        {
          "ID": "24033750-4d85-4b7d-aa00-4fcc7453baf4",
          "ParameterCode": "ParameterCode-24033750",
          "ParameterName": "ParameterName-24033750",
          "ParentParameterCode": "ParentParameterCode-24033750",
          "ParentParameterName": "ParentParameterName-24033750",
          "AttributeID": "AttributeID-24033750",
          "Attribute": "Attribute-24033750",
          "Observation": "Observation-24033750",
          "InstrumentId": "InstrumentId-24033750",
          "InstrumentDesc": "InstrumentDesc-24033750",
          "Status": "Status-24033750",
          "Remarks1": "Remarks1-24033750",
          "Remarks2": "Remarks2-24033750"
        }
      ]
    },
    {
      "ID": "19196689-8b96-4d1f-a13b-8322e9f71c11",
      "SerialBatchNumber": "SerialBatchNumber-19196689",
      "Quantity": 97.15,
      "Status": "Status-19196689",
      "UsageDecisionStockType": "UsageDecisionStockType-19196689",
      "StorageLocation": "StorageLocation-19196689",
      "InspectionPlanStatus": "InspectionPlanStatus-19196689",
      "ParametersDetails": [
        {
          "ID": "67407745-2071-4d52-ae2b-b102212c88f0",
          "ParameterCode": "ParameterCode-6740774",
          "ParameterName": "ParameterName-6740774",
          "ParentParameterCode": "ParentParameterCode-6740774",
          "ParentParameterName": "ParentParameterName-6740774",
          "AttributeID": "AttributeID-6740774",
          "Attribute": "Attribute-6740774",
          "Observation": "Observation-6740774",
          "InstrumentId": "InstrumentId-6740774",
          "InstrumentDesc": "InstrumentDesc-6740774",
          "Status": "Status-6740774",
          "Remarks1": "Remarks1-6740774",
          "Remarks2": "Remarks2-6740774"
        },
        {
          "ID": "6740775a-d563-4e0f-922b-5998b0c3fe0b",
          "ParameterCode": "ParameterCode-6740775",
          "ParameterName": "ParameterName-6740775",
          "ParentParameterCode": "ParentParameterCode-6740775",
          "ParentParameterName": "ParentParameterName-6740775",
          "AttributeID": "AttributeID-6740775",
          "Attribute": "Attribute-6740775",
          "Observation": "Observation-6740775",
          "InstrumentId": "InstrumentId-6740775",
          "InstrumentDesc": "InstrumentDesc-6740775",
          "Status": "Status-6740775",
          "Remarks1": "Remarks1-6740775",
          "Remarks2": "Remarks2-6740775"
        }
      ]
    }
  ]
}


### RecordResultSAPHead
# @name RecordResultSAPHead_DELETE
DELETE {{server}}/odata/v4/record-result-sap/RecordResultSAPHead/15316918-991c-4879-860b-2925b51287a1
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### RecordResultSerialBatchDetail
# @name RecordResultSerialBatchDetail_GET
GET {{server}}/odata/v4/record-result-sap/RecordResultSerialBatchDetail
Authorization: Basic {{username}}:{{password}}


### RecordResultSerialBatchDetail
# @name RecordResultSerialBatchDetail_POST
POST {{server}}/odata/v4/record-result-sap/RecordResultSerialBatchDetail
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "19196688-b832-4af8-8e27-49a877483332",
  "SerialBatchNumber": "SerialBatchNumber-19196688",
  "Quantity": 18.14,
  "Status": "Status-19196688",
  "UsageDecisionStockType": "UsageDecisionStockType-19196688",
  "StorageLocation": "StorageLocation-19196688",
  "InspectionPlanStatus": "InspectionPlanStatus-19196688",
  "ParametersDetails": [
    {
      "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
      "ParameterCode": "ParameterCode-24033749",
      "ParameterName": "ParameterName-24033749",
      "ParentParameterCode": "ParentParameterCode-24033749",
      "ParentParameterName": "ParentParameterName-24033749",
      "AttributeID": "AttributeID-24033749",
      "Attribute": "Attribute-24033749",
      "Observation": "Observation-24033749",
      "InstrumentId": "InstrumentId-24033749",
      "InstrumentDesc": "InstrumentDesc-24033749",
      "Status": "Status-24033749",
      "Remarks1": "Remarks1-24033749",
      "Remarks2": "Remarks2-24033749"
    },
    {
      "ID": "24033750-4d85-4b7d-aa00-4fcc7453baf4",
      "ParameterCode": "ParameterCode-24033750",
      "ParameterName": "ParameterName-24033750",
      "ParentParameterCode": "ParentParameterCode-24033750",
      "ParentParameterName": "ParentParameterName-24033750",
      "AttributeID": "AttributeID-24033750",
      "Attribute": "Attribute-24033750",
      "Observation": "Observation-24033750",
      "InstrumentId": "InstrumentId-24033750",
      "InstrumentDesc": "InstrumentDesc-24033750",
      "Status": "Status-24033750",
      "Remarks1": "Remarks1-24033750",
      "Remarks2": "Remarks2-24033750"
    }
  ]
}


### RecordResultSerialBatchDetail
# @name RecordResultSerialBatchDetail_PATCH
PATCH {{server}}/odata/v4/record-result-sap/RecordResultSerialBatchDetail/19196688-b832-4af8-8e27-49a877483332
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "19196688-b832-4af8-8e27-49a877483332",
  "SerialBatchNumber": "SerialBatchNumber-19196688",
  "Quantity": 18.14,
  "Status": "Status-19196688",
  "UsageDecisionStockType": "UsageDecisionStockType-19196688",
  "StorageLocation": "StorageLocation-19196688",
  "InspectionPlanStatus": "InspectionPlanStatus-19196688",
  "ParametersDetails": [
    {
      "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
      "ParameterCode": "ParameterCode-24033749",
      "ParameterName": "ParameterName-24033749",
      "ParentParameterCode": "ParentParameterCode-24033749",
      "ParentParameterName": "ParentParameterName-24033749",
      "AttributeID": "AttributeID-24033749",
      "Attribute": "Attribute-24033749",
      "Observation": "Observation-24033749",
      "InstrumentId": "InstrumentId-24033749",
      "InstrumentDesc": "InstrumentDesc-24033749",
      "Status": "Status-24033749",
      "Remarks1": "Remarks1-24033749",
      "Remarks2": "Remarks2-24033749"
    },
    {
      "ID": "24033750-4d85-4b7d-aa00-4fcc7453baf4",
      "ParameterCode": "ParameterCode-24033750",
      "ParameterName": "ParameterName-24033750",
      "ParentParameterCode": "ParentParameterCode-24033750",
      "ParentParameterName": "ParentParameterName-24033750",
      "AttributeID": "AttributeID-24033750",
      "Attribute": "Attribute-24033750",
      "Observation": "Observation-24033750",
      "InstrumentId": "InstrumentId-24033750",
      "InstrumentDesc": "InstrumentDesc-24033750",
      "Status": "Status-24033750",
      "Remarks1": "Remarks1-24033750",
      "Remarks2": "Remarks2-24033750"
    }
  ]
}


### RecordResultSerialBatchDetail
# @name RecordResultSerialBatchDetail_DELETE
DELETE {{server}}/odata/v4/record-result-sap/RecordResultSerialBatchDetail/19196688-b832-4af8-8e27-49a877483332
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### RecordResultParametersDetail
# @name RecordResultParametersDetail_GET
GET {{server}}/odata/v4/record-result-sap/RecordResultParametersDetail
Authorization: Basic {{username}}:{{password}}


### RecordResultParametersDetail
# @name RecordResultParametersDetail_POST
POST {{server}}/odata/v4/record-result-sap/RecordResultParametersDetail
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
  "ParameterCode": "ParameterCode-24033749",
  "ParameterName": "ParameterName-24033749",
  "ParentParameterCode": "ParentParameterCode-24033749",
  "ParentParameterName": "ParentParameterName-24033749",
  "AttributeID": "AttributeID-24033749",
  "Attribute": "Attribute-24033749",
  "Observation": "Observation-24033749",
  "InstrumentId": "InstrumentId-24033749",
  "InstrumentDesc": "InstrumentDesc-24033749",
  "Status": "Status-24033749",
  "Remarks1": "Remarks1-24033749",
  "Remarks2": "Remarks2-24033749"
}


### RecordResultParametersDetail
# @name RecordResultParametersDetail_PATCH
PATCH {{server}}/odata/v4/record-result-sap/RecordResultParametersDetail/24033749-a17d-43d1-b47f-d475cdb5caca
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "24033749-a17d-43d1-b47f-d475cdb5caca",
  "ParameterCode": "ParameterCode-24033749",
  "ParameterName": "ParameterName-24033749",
  "ParentParameterCode": "ParentParameterCode-24033749",
  "ParentParameterName": "ParentParameterName-24033749",
  "AttributeID": "AttributeID-24033749",
  "Attribute": "Attribute-24033749",
  "Observation": "Observation-24033749",
  "InstrumentId": "InstrumentId-24033749",
  "InstrumentDesc": "InstrumentDesc-24033749",
  "Status": "Status-24033749",
  "Remarks1": "Remarks1-24033749",
  "Remarks2": "Remarks2-24033749"
}


### RecordResultParametersDetail
# @name RecordResultParametersDetail_DELETE
DELETE {{server}}/odata/v4/record-result-sap/RecordResultParametersDetail/24033749-a17d-43d1-b47f-d475cdb5caca
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
