@server=http://localhost:4004
@username=alice
@password=


### RecordResultHead
# @name RecordResultHead_GET
GET {{server}}/odata/v4/record-result/RecordResultHead
Authorization: Basic {{username}}:{{password}}


### RecordResultHead
# @name RecordResultHead_POST
POST {{server}}/odata/v4/record-result/RecordResultHead
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15926449-fd08-49c5-b702-ec24f9fb4d7c",
  "InspectionLot": "InspectionLot-1592644",
  "Material": "Material-1592644",
  "Plant": "Plant-1592644",
  "ManagedBy": "ManagedBy-1592644",
  "SerialNumber": "SerialNumber-1592644",
  "PostDate": "2001-01-12",
  "EOI": "EOI-1592644",
  "Quantity": 65.28,
  "AcceptedQuantity": 44.23,
  "RejectedQuantity": 91.15,
  "Status": "Status-1592644",
  "ParameterDetails": [
    {
      "ID": "31226510-4a9c-464c-b864-4c8186726ebd",
      "ParameterCode": "ParameterCode-31226510",
      "ParameterName": "ParameterName-31226510",
      "Attribute": "Attribute-31226510",
      "Observation": "Observation-31226510",
      "InstrumentId": "InstrumentId-31226510",
      "InstrumentDesc": "InstrumentDesc-31226510",
      "Status": "Status-31226510",
      "Remarks1": "Remarks1-31226510",
      "Remarks2": "Remarks2-31226510"
    },
    {
      "ID": "31226511-c126-426e-b92d-dbf651fe0ed1",
      "ParameterCode": "ParameterCode-31226511",
      "ParameterName": "ParameterName-31226511",
      "Attribute": "Attribute-31226511",
      "Observation": "Observation-31226511",
      "InstrumentId": "InstrumentId-31226511",
      "InstrumentDesc": "InstrumentDesc-31226511",
      "Status": "Status-31226511",
      "Remarks1": "Remarks1-31226511",
      "Remarks2": "Remarks2-31226511"
    }
  ]
}


### RecordResultHead
# @name RecordResultHead_PATCH
PATCH {{server}}/odata/v4/record-result/RecordResultHead/15926449-fd08-49c5-b702-ec24f9fb4d7c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15926449-fd08-49c5-b702-ec24f9fb4d7c",
  "InspectionLot": "InspectionLot-1592644",
  "Material": "Material-1592644",
  "Plant": "Plant-1592644",
  "ManagedBy": "ManagedBy-1592644",
  "SerialNumber": "SerialNumber-1592644",
  "PostDate": "2001-01-12",
  "EOI": "EOI-1592644",
  "Quantity": 65.28,
  "AcceptedQuantity": 44.23,
  "RejectedQuantity": 91.15,
  "Status": "Status-1592644",
  "ParameterDetails": [
    {
      "ID": "31226510-4a9c-464c-b864-4c8186726ebd",
      "ParameterCode": "ParameterCode-31226510",
      "ParameterName": "ParameterName-31226510",
      "Attribute": "Attribute-31226510",
      "Observation": "Observation-31226510",
      "InstrumentId": "InstrumentId-31226510",
      "InstrumentDesc": "InstrumentDesc-31226510",
      "Status": "Status-31226510",
      "Remarks1": "Remarks1-31226510",
      "Remarks2": "Remarks2-31226510"
    },
    {
      "ID": "31226511-c126-426e-b92d-dbf651fe0ed1",
      "ParameterCode": "ParameterCode-31226511",
      "ParameterName": "ParameterName-31226511",
      "Attribute": "Attribute-31226511",
      "Observation": "Observation-31226511",
      "InstrumentId": "InstrumentId-31226511",
      "InstrumentDesc": "InstrumentDesc-31226511",
      "Status": "Status-31226511",
      "Remarks1": "Remarks1-31226511",
      "Remarks2": "Remarks2-31226511"
    }
  ]
}


### RecordResultHead
# @name RecordResultHead_DELETE
DELETE {{server}}/odata/v4/record-result/RecordResultHead/15926449-fd08-49c5-b702-ec24f9fb4d7c
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### RecordResultDetail
# @name RecordResultDetail_GET
GET {{server}}/odata/v4/record-result/RecordResultDetail
Authorization: Basic {{username}}:{{password}}


### RecordResultDetail
# @name RecordResultDetail_POST
POST {{server}}/odata/v4/record-result/RecordResultDetail
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31226510-4a9c-464c-b864-4c8186726ebd",
  "ParameterCode": "ParameterCode-31226510",
  "ParameterName": "ParameterName-31226510",
  "Attribute": "Attribute-31226510",
  "Observation": "Observation-31226510",
  "InstrumentId": "InstrumentId-31226510",
  "InstrumentDesc": "InstrumentDesc-31226510",
  "Status": "Status-31226510",
  "Remarks1": "Remarks1-31226510",
  "Remarks2": "Remarks2-31226510"
}


### RecordResultDetail
# @name RecordResultDetail_PATCH
PATCH {{server}}/odata/v4/record-result/RecordResultDetail/31226510-4a9c-464c-b864-4c8186726ebd
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31226510-4a9c-464c-b864-4c8186726ebd",
  "ParameterCode": "ParameterCode-31226510",
  "ParameterName": "ParameterName-31226510",
  "Attribute": "Attribute-31226510",
  "Observation": "Observation-31226510",
  "InstrumentId": "InstrumentId-31226510",
  "InstrumentDesc": "InstrumentDesc-31226510",
  "Status": "Status-31226510",
  "Remarks1": "Remarks1-31226510",
  "Remarks2": "Remarks2-31226510"
}


### RecordResultDetail
# @name RecordResultDetail_DELETE
DELETE {{server}}/odata/v4/record-result/RecordResultDetail/31226510-4a9c-464c-b864-4c8186726ebd
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
